name: actions7 list-syntax

on:
  workflow_dispatch:
  push:
    branches: [main, sub]

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      JOB_NAME: job1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: step for main
        env: 
          STEP_NAME: mystep1
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        run: |
          git fetch --prune --unshallow
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "This is $JOB_NAME.$STEP_NAME."
          echo "The changed file is $CHANGED_FILES"
