name: Custom Actions

on:
  workflow_dispatch:
    inputs:
      firstNameStudent:
        description: 'First name of student'
        required: false
        default: '1'
      studentGrade:
        description: 'Grade of the student'
        required: true

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run Hello World Action
      uses: ./
      with:
        firstNameStudent: ${{ github.event.inputs.firstNameStudent }}
        studentGrade: ${{ github.event.inputs.studentGrade }}

    - name: workflow commands logging messages
      run: |
        echo "::debug::This is a debug message"
        echo "This is an info message"
        echo "::error::This is an error message"
        echo "::warning::This is a warning message"

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ./artifact/artifact.txt
        retention-days: 15
