name: workflow_dispatch7 list-syntax

on:
  workflow_dispatch:
  push:
    branches: [main, sub]

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      JOB_NAME: job1
    steps:
      - name: step for main
        env: 
          STEP_NAME: mystep1
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        run: echo "this is $JOB_NAME.$STEP_NAME"
