name: workflow_dispatch6 env、必須review

on:
  workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  job1:
    runs-on: ubuntu-latest
    environment:
      name: environment1
    steps:
      - run: echo "sleep10中..." && sleep 10
  
  job2:
    runs-on: ubuntu-latest
    environment:
      name: environment1
    steps:
      - run: echo "sleep20中..." && sleep 20

  job3:
    runs-on: ubuntu-latest
    needs: job1
    environment:
      name: environment1
    steps:
      - run: echo "sleep10中..." && sleep 10
