name: workflow_dispatch sample 4

on:
  workflow_dispatch

jobs:
  normal-job:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          echo "sleep5中..."
          sleep 5

  concurrency-job:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          echo "sleep60中..."
          sleep 60

  dependent-job:
    runs-on: ubuntu-20.04
    needs:
      - normal-job
    steps:
      - run:  |
          echo "sleep20中..."
          sleep 20

  after-job:
    runs-on: ubuntu-20.04
    needs:
      - dependent-job
    steps:
      - run:  |
          echo "sleep5中..."
          sleep 5
