name: workflow_dispatch7 list-syntax

on:
  workflow_dispatch:
  push:
    branches: [main, sub]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step for main
        id: mystep1
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        run: echo "this is job1.${{ steps.mystep1.outputs.name }}"
